create table REST_AD(
AD_ID INT NOT NULL,
REST_ID INT NOT NULL,
AD_NAME VARCHAR(50) NOT NULL, 
AD_PIC LONGBLOB,
AD_INTRO VARCHAR(200),
AD_TIME VARCHAR(50),
PRIMARY KEY (AD_ID),
FOREIGN KEY (REST_ID)REFERENCES REST_LIST(REST_ID));

INSERT INTO REST_AD(
AD_ID, 
REST_ID,
AD_NAME,
AD_INTRO,
AD_TIME)VALUE(
1,
1,
"慶端午，肉粽吃起來",
"你吃的是北部粽?還是南部粽?快來JAVA STEAK HOUSE品嘗創新料理美式肉粽",
"2022-06-22~2022-07-22");

INSERT INTO REST_AD(
AD_ID, 
REST_ID,
AD_NAME,
AD_INTRO,
AD_TIME)VALUE(
2,
1,
"暑假動起來,小小廚神體驗營",
"兩人同行，家長免費，製作紅蘿蔔蛋糕",
"2022-07-01~2022-08-31");

INSERT INTO REST_AD(
AD_ID, 
REST_ID,
AD_NAME,
AD_INTRO,
AD_TIME)VALUE(
3,
2,
"以拉一下馬賽",
"馬薩卡哦一西一修尼塔杯魯",
"2022-07-01~2022-08-31");

INSERT INTO REST_AD(
AD_ID, 
REST_ID,
AD_NAME,
AD_INTRO,
AD_TIME)VALUE(
4,
2,
"KONICHIWA",
"WATASHIWA NIHON JIN DESU",
"2022-07-01~2022-08-31");

INSERT INTO REST_AD(
AD_ID, 
REST_ID,
AD_NAME,
AD_INTRO,
AD_TIME)VALUE(
5,
3,
"NEFILX AND CHILL",
"DO YOU WANT SOME COFFEE? MY CAT CAN DO BACKFILP",
"2022-07-01~2022-08-31");