

-- 前置作業
DROP TABLE SALES_ORDER_ITEM;
DROP TABLE SALES_ORDER_HEADER;
DROP TABLE SALES_ORDER_STATUS;

-- 建立訂單狀態資料表
CREATE TABLE SALES_ORDER_STATUS(
	SALES_ORDER_STATUS_ID INT NOT NULL PRIMARY KEY COMMENT '訂單狀態ID',
    SALES_ORDER_STATUS VARCHAR(25) NOT NULL COMMENT '訂單狀態名稱'
);

-- 新增訂單狀態資料
INSERT INTO SALES_ORDER_STATUS(SALES_ORDER_STATUS_ID, SALES_ORDER_STATUS)
VALUES(1, "等待付款"),
	  (2, "已付款"),
      (3, "已完成"),
      (4, "已取消"),
      (5, "客服處理中");
      
select * from SALES_ORDER_STATUS;


-- 建立訂單資料表
CREATE TABLE SALES_ORDER_HEADER(
	SALES_ORDER_HEADER_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '訂單編號',
    USER_ID INT NOT NULL COMMENT '使用者流水編號',
    CREATE_DATE DATE NOT NULL COMMENT '訂單建立日',
    ORDER_START_DATE DATE NOT NULL COMMENT '入住日期',
    ORDER_END_DATE DATE NOT NULL COMMENT '退房日期',
    ORDER_CHANGE_DATE DATE COMMENT '訂單修改日期',
    SALES_ORDER_STATUS_ID INT NOT NULL COMMENT '訂單狀態ID',
	ORDER_REMARK VARCHAR(50) COMMENT'訂單備註',
    ORDER_ROOM_PRICE INT NOT NULL COMMENT '房間總額',
    ORDER_JOURNEY_PRICE INT COMMENT '行程總額',
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
    FOREIGN KEY (SALES_ORDER_STATUS_ID) REFERENCES SALES_ORDER_STATUS(SALES_ORDER_STATUS_ID)
);

-- SELECT * FROM SALES_ORDER_HEADER;

INSERT INTO SALES_ORDER_HEADER(USER_ID, CREATE_DATE, ORDER_START_DATE, ORDER_END_DATE, ORDER_CHANGE_DATE, SALES_ORDER_STATUS_ID, ORDER_REMARK, ORDER_ROOM_PRICE, ORDER_JOURNEY_PRICE)
VALUES
	  (1, '2022-05-22', '2022-06-22', '2022-06-23', '2022-05-23', 2, "獨身男子的行程: 一房一行程，有修改日期的訂單，狀態已付款", 5000, 700),
	  (3, '2022-04-02', '2022-05-02', '2022-05-09', NULL, 1, "小屁孩安妮亞:一房一行程，無修改日期的訂單，狀態未付款", 8000, 1500),
	  (4, '2022-04-02', '2022-05-02', '2022-05-09', NULL, 2, "家庭的行程: 兩房有行程，無修改日期的訂單，狀態已付款", 56000, 1500),
	  (2, '2022-06-01', '2022-07-01', '2022-07-02', '2022-06-02', 4, "自動取消的行程: 沒付錢，系統要自動更改修改日期的訂單，狀態已取消", 5000, 300),
	  (2, '2022-06-02', '2022-07-01', '2022-07-02', NULL, 1, "隔天趕快再訂的行程: 跟上一筆訂單內容相同，狀態已付款", 5000, 300),
	  (5, '2022-04-02', '2022-05-02', '2022-05-09', NULL, 3, "隨便建立一張已完成的訂單", 154000 , NULL);

SELECT * FROM SALES_ORDER_HEADER;


-- 建立訂單明細資料表
CREATE TABLE SALES_ORDER_ITEM(
	SALES_ORDER_ITEM_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '訂單明細ID',
    SALES_ORDER_HEADER_ID INT NOT NULL COMMENT '訂單編號',
    ROOM_STYLE_ID INT NOT NULL COMMENT '房型ID',
    ORDER_ROOM_QUANTITY INT NOT NULL COMMENT '訂房數量',
    ORDER_ROOM_PRICE INT NOT NULL COMMENT '房間單價',
    FOREIGN KEY (SALES_ORDER_HEADER_ID) REFERENCES SALES_ORDER_HEADER(SALES_ORDER_HEADER_ID),
    FOREIGN KEY (ROOM_STYLE_ID) REFERENCES ROOM_STYLE(ROOM_STYLE_ID)
    );
    
-- 新增訂單明細資料表
INSERT INTO SALES_ORDER_ITEM(SALES_ORDER_HEADER_ID, ROOM_STYLE_ID, ORDER_ROOM_QUANTITY, ORDER_ROOM_PRICE)
VALUES
	(1,1,1,5000),
    (2,2,1,8000),
    (3,2,1,8000),
    (3,2,1,8000),
    (4,1,1,5000),
    (5,4,1,5000),
    (6,3,2,7000),
    (6,1,1,8000);
    
-- 檢查用
SELECT * FROM SALES_ORDER_STATUS;
SELECT * FROM SALES_ORDER_HEADER;
SELECT * FROM SALES_ORDER_ITEM;