/*
SQLyog Community v13.1.9 (64 bit)
MySQL - 8.0.29 : Database - AGJS
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`AGJS` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;

USE `AGJS`;

/*Table structure for table `ROOM` */

DROP TABLE IF EXISTS `ROOM`;

CREATE TABLE `ROOM` (
  `ROOM_ID` int NOT NULL AUTO_INCREMENT COMMENT '房號',
  `ROOM_STYLE_ID` int DEFAULT NULL,
  PRIMARY KEY (`ROOM_ID`),
  KEY `ROOM_STYLE_ID_idx` (`ROOM_STYLE_ID`),
  CONSTRAINT `ROOM_STYLE_ID` FOREIGN KEY (`ROOM_STYLE_ID`) REFERENCES `ROOM_STYLE` (`ROOM_STYLE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=503 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='房間';

/*Data for the table `ROOM` */

insert  into `ROOM`(`ROOM_ID`,`ROOM_STYLE_ID`) values 
(201,1),
(202,2),
(501,2),
(301,3),
(502,3),
(302,4);

/*Table structure for table `ROOM_STYLE` */

DROP TABLE IF EXISTS `ROOM_STYLE`;

CREATE TABLE `ROOM_STYLE` (
  `ROOM_STYLE_ID` int NOT NULL AUTO_INCREMENT COMMENT '房型ID',
  `ROOM_NAME` varchar(20) NOT NULL COMMENT '房型名稱',
  `ROOM_QUANTITY` int NOT NULL COMMENT '房數',
  `BED_TYPE` varchar(10) NOT NULL COMMENT '床型',
  `ROOM_TYPE` varchar(10) NOT NULL COMMENT '房型種類',
  `ORDER_ROOM_PRICE` int NOT NULL COMMENT '房間單價',
  `ROOM_DESCRIPTION` text NOT NULL COMMENT '房型描述',
  PRIMARY KEY (`ROOM_STYLE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='房型';

/*Data for the table `ROOM_STYLE` */

insert  into `ROOM_STYLE`(`ROOM_STYLE_ID`,`ROOM_NAME`,`ROOM_QUANTITY`,`BED_TYPE`,`ROOM_TYPE`,`ORDER_ROOM_PRICE`,`ROOM_DESCRIPTION`) values 
(1,'山景標準房',5,'兩小床/一大床','雙人房',5000,'簡約舒適、度假首選'),
(2,'山景雅致房',5,'兩大床','四人房',8000,'遠離塵囂、感受靜謐'),
(3,'海景標準房',5,'兩小床/一大床','雙人房',7000,'碧海藍天、體驗經典'),
(4,'海景雅致房',5,'兩大床','四人房',10000,'島嶼記憶、度假美夢');

/*Table structure for table `ROOM_USED_RECORD` */

DROP TABLE IF EXISTS `ROOM_USED_RECORD`;

CREATE TABLE `ROOM_USED_RECORD` (
  `ROOM_USED_RECORD__ID` int NOT NULL AUTO_INCREMENT COMMENT '客房使用紀錄ID',
  `ROOM_ID` int NOT NULL COMMENT '房號',
  `SALES_ORDER_HEADER_ID` int DEFAULT NULL COMMENT '訂單編號',
  `ORDER_START_DATE` date NOT NULL COMMENT '入住日期',
  `ORDER_END_DATE` date NOT NULL COMMENT '退房日期',
  `USER_NAME` varchar(30) DEFAULT NULL COMMENT '會員姓名',
  `SOURCE` tinyint NOT NULL COMMENT '來源',
  PRIMARY KEY (`ROOM_USED_RECORD__ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='客房使用紀錄';

/*Data for the table `ROOM_USED_RECORD` */

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
