-- 建立 行程類型 TABLE
CREATE TABLE `AGJS`.`JOURNEY_TYPE` (
  `JOURNEY_TYPE_ID` INT NOT NULL AUTO_INCREMENT,
  `JOURNEY_TYPE` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`JOURNEY_TYPE_ID`))
COMMENT = '行程類型';

-- 新增五筆行程類型
insert into JOURNEY_TYPE(JOURNEY_TYPE)
values ('海洋游趣'),('深度之旅'),('藝文風尚'),('歷史巡禮'),('美食之旅');

-- 建立 加購行程 TABLE
CREATE TABLE `AGJS`.`JOURNEY` (
  `JOURNEY_ID` INT NOT NULL AUTO_INCREMENT COMMENT '行程編號' PRIMARY KEY ,
  `JOURNEY_NAME` VARCHAR(20) NOT NULL COMMENT '行程名稱',
  `JOURNEY_TYPE_ID` INT NOT NULL COMMENT 'FK_行程類型編號',
  `JOURNEY_PRICE` INT NOT NULL COMMENT '行程價格',
  `JOURNEY_PRICE_CHILD` INT NOT NULL COMMENT '行程價格(兒童)',
  `APPLY_LIMIT` INT NOT NULL COMMENT '報名人數上限',
  `JOURNEY_PICTURE` BLOB NULL COMMENT '行程照片',
  `JOURNET_INFO` TEXT(1000) NULL COMMENT '行程介紹',
  `LAUNCHED` TINYINT NOT NULL COMMENT '是否上架(是否開放加購)',
  CONSTRAINT `JOURNEY_TYPE_ID`
    FOREIGN KEY (`JOURNEY_TYPE_ID`)
    REFERENCES `AGJS`.`JOURNEY_TYPE` (`JOURNEY_TYPE_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
COMMENT = '加購行程';

-- 新增兩筆 加購行程 
insert into JOURNEY(JOURNEY_NAME, JOURNEY_TYPE_ID, JOURNEY_PRICE, JOURNEY_PRICE_CHILD, APPLY_LIMIT, LAUNCHED)
values ('繁星沙岸', 1, 750, 500, 20, true), 
		('林間巡禮', 2, 900, 650, 35, true);

-- 建立 行程訂單明細 TABLE
CREATE TABLE `AGJS`.`JOURNEY_ITEM` (
  `JOURNEY_ITEM_ID` INT NOT NULL AUTO_INCREMENT COMMENT '行程單編號' PRIMARY KEY,
  `SALES_ORDER_HEADER_ID` INT NOT NULL COMMENT 'FK_訂單編號',
  `JOURNEY_ID` INT NOT NULL COMMENT 'FK_行程編號',
  `ADULTS` INT NULL COMMENT '大人',
  `CHILDREN` INT NULL COMMENT '小孩',
  `JOURNEY_DATE` DATE NOT NULL COMMENT '行程日期',
  CONSTRAINT `JOURNEY_ID`
    FOREIGN KEY (`JOURNEY_ID`)
    REFERENCES `AGJS`.`JOURNEY` (`JOURNEY_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `SALES_ORDER_HEADER_ID`
    FOREIGN KEY (`SALES_ORDER_HEADER_ID`)
    REFERENCES `AGJS`.`SALES_ORDER_HEADER` (`SALES_ORDER_HEADER_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
COMMENT = '行程訂單明細';

-- 新增五筆訂單明細
insert into JOURNEY_ITEM(SALES_ORDER_HEADER_ID, JOURNEY_ID, ADULTS, CHILDREN, JOURNEY_DATE)
values ( 1, 1, 2, 0, 2022-08-25),
		(2, 2, 4, 2, 2022-08-7),
		(3, 2, 2, 0, 2022-08-7),
		(4, 2, 5, 0, 2022-08-20),
		(5, 1, 2, 3, 2022-08-20);





